### ISSUE TITLE
Broken Build due to "CMake 3.5.0 or higher is required.  You are running version 2.8.12.2."

### ISSUE THREAD

**Issue by vorburger** [redhat-developer/che-dockerfiles#50]
Following README and running:

```
docker build \
  -t spring-boot:local \
  -f ./recipes/dockerfiles/spring-boot/Dockerfile \
  ./recipes/
```

currently causes:

```
oc
Loaded plugins: fastestmirror, ovl
Cleaning repos: base centos-sclo-rh centos-sclo-sclo extras updates
Cleaning up list of fastest mirrors
 ---> cb2fca2f77a0
Removing intermediate container f7f9eb11b36a
Step 5/21 : COPY ./context/nss_wrapper.install /tmp/install/
 ---> 6b6487e52478
Removing intermediate container 2ccfc0a0c7e8
Step 6/21 : RUN sudo chown user:user /tmp/install /tmp/install/* &&     /tmp/install/nss_wrapper.install &&     sudo rm -rf /tmp/install
 ---> Running in 77b076bcf45d

================================================================================
 Package             Arch        Version                     Repository    Size
================================================================================
Installing:
 cmake               x86_64      2.8.12.2-2.el7              base         7.1 M
 gcc                 x86_64      4.8.5-36.el7_6.1            updates       16 M
 make                x86_64      1:3.82-23.el7               base         420 k
Installing for dependencies:
 cpp                 x86_64      4.8.5-36.el7_6.1            updates      5.9 M
 glibc-devel         x86_64      2.17-260.el7_6.3            updates      1.1 M
 glibc-headers       x86_64      2.17-260.el7_6.3            updates      683 k
 kernel-headers      x86_64      3.10.0-957.10.1.el7         updates      8.0 M
 libarchive          x86_64      3.1.2-10.el7_2              base         318 k
 libmpc              x86_64      1.0.1-3.el7                 base          51 k
 lzo                 x86_64      2.06-8.el7                  base          59 k
 mpfr                x86_64      3.1.1-4.el7                 base         203 k

Transaction Summary
================================================================================
Install  3 Packages (+8 Dependent packages)

Total download size: 40 M
Installed size: 89 M

Installed:
  cmake.x86_64 0:2.8.12.2-2.el7          gcc.x86_64 0:4.8.5-36.el7_6.1         
  make.x86_64 1:3.82-23.el7             

Dependency Installed:
  cpp.x86_64 0:4.8.5-36.el7_6.1                                                 
  glibc-devel.x86_64 0:2.17-260.el7_6.3                                         
  glibc-headers.x86_64 0:2.17-260.el7_6.3                                       
  kernel-headers.x86_64 0:3.10.0-957.10.1.el7                                   
  libarchive.x86_64 0:3.1.2-10.el7_2                                            
  libmpc.x86_64 0:1.0.1-3.el7                                                   
  lzo.x86_64 0:2.06-8.el7                                                       
  mpfr.x86_64 0:3.1.1-4.el7                                                     

Cloning into 'nss_wrapper'...
CMake Error at CMakeLists.txt:2 (cmake_minimum_required):
  CMake 3.5.0 or higher is required.  You are running version 2.8.12.2


-- Configuring incomplete, errors occurred!
The command '/bin/sh -c sudo chown user:user /tmp/install /tmp/install/* &&     /tmp/install/nss_wrapper.install &&     sudo rm -rf /tmp/install' returned a non-zero code: 1
```

@tqvarnst this is exactly the same as what you locally hit as well, right?

@benoitf @dneary are you aware of this problem? Looks like this project as-is is broken...

It's blocking me for https://github.com/tqvarnst/quarkus-workshop/issues/2 so I'll see if I can figure something out (but no guarantees, both time and know how wise).

**Comment by vorburger** [comment]
> see if I can figure something out

OK, so basically the gist of it is that we build [nss_wrapper](https://cwrap.org/nss_wrapper.html) from [its source](https://git.samba.org/?p=nss_wrapper.git;a=summary), right from its latest `master`. 

Now that project (nss_wrapper) at some point after this last worked decided to require [CMake](https://cmake.org/) 3+ - but CentOS (ultimately `FROM registry.centos.org/centos/centos`, but through 5 hoops) gives us CMake 2.8.12.2 on `yum install cmake`.

Can we easily get the newer CMake on CentOS? Or could we use a CentOS package for nss_wrapper?

**Comment by vorburger** [comment]
> Can we easily get the newer CMake on CentOS?

according to e.g. this StackOverflow post, there should be a `cmake3`, but that's NOK:

```
docker run --rm --name centos-cmake3-test registry.centos.org/centos/centos yum install -y cmake3
Loaded plugins: fastestmirror, ovl
Determining fastest mirrors
 * base: mirror.spreitzer.ch
 * extras: mirror.spreitzer.ch
 * updates: mirror.spreitzer.ch
No package cmake3 available.
Error: Nothing to do
```

**Comment by vorburger** [comment]
> Is it in EPEL?

yup! This actually works:

    docker run --rm --name centos-cmake3-test registry.centos.org/centos/centos bash -c "yum install -y epel-release ; yum install -y cmake3"

I'll try to work this into the respective script in this project ASAP, and if successful raise a PR.

PS: Not 100% sure how acceptable it is to use a package from EPEL in this project (for downstream product packages at certain vendors), but seeing how we build nss_wrapper from its master source instead of via a supported packaged, that is perhaps the least of the worries? :smiling_imp: I'll ignore that aspect and let others deal with it separately later.

**Comment by dneary** [comment]
I think if it is *only* the build tool that is being pulled in, that should be fine. If there are other runtime dependencies being pulled in from EPEL, that might be an issue. Then again, we're not promising support (or supportability) so this might be good either way.

**Comment by vorburger** [comment]
> work this into the respective script in this project ASAP, and if successful raise a PR.

Done, so one way to solve this problem would be #53.

> Or could we use a CentOS package for nss_wrapper?

There actually is (but again in EPEL, only), check this out (and note how it loads of Perl stuff?!?):

    docker run --rm --name centos-nss_wrapper-test registry.centos.org/centos/centos bash -c "yum install -y epel-release ; yum install -y nss_wrapper"

so an alternative solution would be #52.

I'll let others choose which solution they prefer (they are competing alternatives, don't merge both).

**Comment by vorburger** [comment]
@ibuziuk or @l0rd review and merge either #52 (better, IMHO) or #53 to fix this?

**Comment by l0rd** [comment]
I love #52
